### ISSUE TITLE
Appointments CRUD needs to be done.

### ISSUE THREAD

**Issue by Smao0875** [Smao0875/TcmFrontEnd#4]
Events are already hooked up.
Ready to the next step.

**Comment by JenHZ** [comment]
What is the requirement for this task ?  Change the metod sequence in appointment.service.ts to follow CRUD ?

**Comment by Smao0875** [comment]
Not really.
First I need to know whether you can show the appointments correctly or not.
When the user clicks a day, there should be a pop up window tells user to add a appointment for a certain patient.
When the user resizes an appointment, we should update the information of the appointments.

Actually the work of service is almost done.
We need to UI part.

**Comment by JenHZ** [comment]
I can see the appointments in practitioner page. There are appointments shown in the calendar in Receptionist page.
I will try to work on this.

**Comment by Smao0875** [comment]
It's already done.
