### ISSUE TITLE
The width of Payment list is too narrow.

### ISSUE THREAD

**Issue by Smao0875** [Smao0875/TcmFrontEnd#9]
I tried to expand it but didn't get any luck.

**Comment by Smao0875** [comment]
Tried a few times. No luck.
Jen, could you take a look?
Thanks.

**Comment by JenHZ** [comment]
I will.

**Comment by JenHZ** [comment]
![payment](https://user-images.githubusercontent.com/15660517/38593696-b3d85af0-3d10-11e8-9f62-2a976822642e.png)

Do you mean width of this ?

**Comment by Smao0875** [comment]
Good job.
I never thought about assigning fixed value to those controls.
